### PR TITLE
Mark legacy functions deprecated

### PR DESCRIPTION
**Pull request by rbt**
Any objection to marking the legacy functions as deprecated?

I believe this was discussed in #110.

### CODE REVIEW

**Comment by Altai-man** [comment]
No believe, but maybe it will be better to set a clear deprecation removal planned date so that people could take it more seriously?

**Comment by rbt** [comment]
Perhaps give 2 years notice? Remove them (and others already marked deprecated) in June 2022?

Should that time period be in the deprecation message? README? Or just a comment in the code?

**Comment by Altai-man** [comment]
I'd say a year is enough, but 2 years are okay. Sadly, don't have too much experience in this.
As for notice - deprecation message for sure. Direct warnings are much more clear than readme or comments somewhere deep in implementation.

**Comment by rbt** [comment]
I thought DEPRECATED would allow a date to be provided but the wording wrapped around the provided text makes it quite awkward to read.

I've opted to specify the date for removal in the README.

Also updated tests to remove use of legacy functions.

**Pull request merged**
